name: chatify
description: "Applications for messaging, calling and creating shared groups"

publish_to: 'none'

version: 1.2.18+734

environment:
  sdk: '>=3.4.3 <4.0.0'

#-------------------- PACKAGES --------------------#

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Utility Packages
  http: ^1.4.0
  intl: ^0.20.2
  path: ^1.9.1
  logger: ^2.5.0

  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  emoji_picker_flutter: ^4.3.0
  gif: ^2.3.0
  flutter_notification_channel: ^3.1.1
  image_gallery_saver_plus: ^4.0.1
  dio: ^5.8.0+1
  audioplayers: ^6.4.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  yaml: ^3.1.3
  agora_rtc_engine: ^6.5.2
  video_player: ^2.10.0
  file_picker: ^10.1.9
  flutter_cache_manager: ^3.4.1
  connectivity_plus: ^6.1.4
  record: ^6.0.0
  share_plus: ^11.0.0
  receive_sharing_intent: ^1.8.1
  provider: ^6.1.5
  camera: ^0.11.1
  photo_manager: ^3.7.1
  vector_math: ^2.1.4
  mailer: ^6.4.1
  audio_session: ^0.2.2
  dotted_border: ^3.0.1
  qr_flutter: ^4.1.0
  android_intent_plus: ^5.3.0
  shimmer: ^3.0.0
  flutter_sound: ^9.28.0
  flutter_svg: ^1.1.6
  yandex_mapkit: ^4.1.0
  flutter_contacts: ^1.1.9+2
  local_auth: ^2.3.0
  mime: ^2.0.0
  flutter_dotenv: ^5.2.1
  bitsdojo_window: ^0.1.6
  window_manager: ^0.4.3
  camera_windows: ^0.2.6+2
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  win32: ^5.12.0
  ffi: ^2.1.4
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.5
  process_run: ^1.2.4
  universal_html: ^2.2.4
  video_thumbnail: ^0.5.6
  flutter_webrtc: ^0.14.1
  flutter_local_notifications: ^19.3.0
  uuid: ^4.5.1
  image: ^4.5.4
  flutter_markdown_plus: ^1.0.3

  # Icons
  akar_icons_flutter: ^1.1.21
  cupertino_icons: ^1.0.8
  fluentui_system_icons: ^1.1.273
  majesticons_flutter: ^0.0.1
  bootstrap_icons: ^1.11.3
  iconic: ^0.1.0
  mono_icons: ^1.0.0+2
  lucide_icons: ^0.257.0
  iconforest_clarity: ^1.0.0+1
  flutter_phosphor_icons: ^0.0.1+6
  hugeicons: ^0.0.10
  heroicons: ^0.7.0
  tabler_icons: ^2.5.0+1
  flutter_material_design_icons: ^1.1.7447
  ionicons: ^0.2.2
  evil_icons_flutter: ^0.5.0
  carbon_icons: ^0.0.1+2
  iconify_flutter: ^0.0.5
  feather_icons: ^1.2.0
  icon_forest: ^1.1.8
  radix_icons: ^1.0.1
  iconsax_plus: ^1.0.0
  jam_icons: ^0.0.1
  phosphor_flutter: ^2.1.0
  iconoir_icons: ^0.1.1

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  google_sign_in: ^7.1.1
  firebase_storage: ^12.4.9
  firebase_messaging: ^15.2.9
  firebase_app_check: ^0.3.2+9
  googleapis_auth: ^2.0.0
  googleapis: ^14.0.0

#-------------------- ./ PACKAGES END --------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Utility Packages
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  intl_utils: ^2.8.11
  build_runner: ^2.6.0
  build_config: ^1.1.2
  build_version: ^2.1.1

flutter_intl:
  enabled: true
  arb_dir: lib/localization/l10n
  output_dir: lib/generated/l10n

flutter:
  uses-material-design: true
  generate: true

  #-------------------- LOCAL ASSETS --------------------#
  assets:
    - assets/fonts/
    - assets/logos/
    - assets/icons/auth/
    - assets/images/
    - assets/images/wallpapers/
    - assets/images/solid_colors/
    - assets/sounds/
    - assets/background/
    - assets/vectors/
    - assets/vectors/flags/
    - assets/licenses/

  #-------------------- LOCAL FONTS --------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica/Helvetica-Light.otf
          weight: 300
        - asset: assets/fonts/Helvetica/Helvetica-Regular.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Helvetica/Helvetica-Italic.otf
          weight: 500
        - asset: assets/fonts/Helvetica/Helvetica-Bold.otf
          weight: 800
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi/Satoshi-Regular.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Satoshi/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi/Satoshi-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi/Satoshi-Bold.ttf
          weight: 800
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/Coolvetica/Coolvetica-Italic.otf
          style: italic
        - asset: assets/fonts/Coolvetica/Coolvetica-Regular.otf
          weight: 400

