import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../../../../localization/app_localizations.dart';
import '../../../../utils/constants/app_vectors.dart';
import '../../models/country.dart';

final List<Country> countries = [
  Country('+61', 'AU', 'Австралия', 'Australia', ChatifyVectors.aus),
  Country('+43', 'AT', 'Австрия', 'Austria', ChatifyVectors.aut),
  Country('+994', 'AZ', 'Азербайджан', 'Azerbaijan', ChatifyVectors.aze),
  Country('+358', 'AX', 'Аландские острова', 'Åland', ChatifyVectors.ala),
  Country('+355', 'AL', 'Албания', 'Shqipëri', ChatifyVectors.ala),
  Country('+213', 'DZ', 'Алжир', 'Algeria', ChatifyVectors.dza),
  Country('+1', 'AS', 'Американское Самоа', 'American Samoa', ChatifyVectors.asm),
  Country('+1', 'AI', 'Ангилья', 'Angullia', ChatifyVectors.aia),
  Country('+376', 'AD', 'Андорра', 'Andorra', ChatifyVectors.and),
  Country('+1', 'AG', 'Антигуа и Барбуда', 'Antigua & Barbuda', ChatifyVectors.atg),
  Country('+244', 'AO', 'Ангола', 'Angola', ChatifyVectors.ago),
  Country('+54', 'AR', 'Аргентина', 'Argentina', ChatifyVectors.arg),
  Country('+374', 'AM', 'Армения', 'Հայաստան', ChatifyVectors.arm),
  Country('+297', 'AW', 'Аруба', 'Aruba', ChatifyVectors.abw),
  Country('+93', 'AF', 'Афганистан', 'افغانستان', ChatifyVectors.afg),
  Country('+973', 'BH', 'Бахрейн', 'البحرين', ChatifyVectors.bhr),
  Country('+880', 'BD', 'Бангладеш', 'বাংলাদেশ', ChatifyVectors.bgd),
  Country('+880', 'BB', 'Барбадос', 'Barbados', ChatifyVectors.brb),
  Country('+375', 'BY', 'Беларусь', '', ChatifyVectors.blr),
  Country('+32', 'BE', 'Бельгия', 'Belgiё', ChatifyVectors.bel),
  Country('+501', 'BZ', 'Белиз', 'Belize', ChatifyVectors.blz),
  Country('+229', 'BJ', 'Бенин', 'Bénin', ChatifyVectors.ben),
  Country('+441', 'BM', 'Бермудские острова', 'Bermuda', ChatifyVectors.bmu),
  Country('+975', 'BT', 'Бутан', 'འབྲུག་ཡུལ', ChatifyVectors.btn),
  Country('+591', 'BO', 'Боливия', 'Bolivia', ChatifyVectors.bol),
  Country('+535', 'BQ', 'Бонайре, Синт-Эстатиус и Саба', 'Bonaire, Sint Eustatius en Saba', ChatifyVectors.bon),
  Country('+387', 'BA', 'Босния и Герциговина', 'Bosna i Hercegovina', ChatifyVectors.bih),
  Country('+267', 'BW', 'Ботсвана', 'Botswana', ChatifyVectors.bwa),
  Country('+55', 'BR', 'Бразилия', 'Brasil', ChatifyVectors.bra),
  Country('+246', 'IO', 'Британская территория Индийского океана', 'British Indian Ocean Territory', ChatifyVectors.iot),
  Country('+673', 'BN', 'Бруней', 'بروني', ChatifyVectors.brn),
  Country('+359', 'BG', 'Болгария', 'България', ChatifyVectors.bgr),
  Country('+1242', 'BS', 'Багамы', 'Bahamas', ChatifyVectors.bhs),
  Country('+226', 'BF', 'Буркина-Фасо', 'Burkina Faso', ChatifyVectors.bfa),
  Country('+257', 'BI', 'Бурунди', 'Burundi', ChatifyVectors.bdi),
  Country('+47', 'BV', 'Буве остров', 'Bouvetøya', ChatifyVectors.bvt),
  Country('+678', 'VU', 'Вануату', 'Vanuatu', ChatifyVectors.vut),
  Country('+379', 'VA', 'Ватикан', 'Civitas Vaticana', ChatifyVectors.vat),
  Country('+44', 'GB', 'Великобритания', 'United Kingdom', ChatifyVectors.gbr),
  Country('+36', 'HU', 'Венгрия', 'Magyarország', ChatifyVectors.hun),
  Country('+58', 'VE', 'Венесуэла', 'Venezuela', ChatifyVectors.ven),
  Country('+850', 'VI', 'Виргинские Острова (США)','U.S Virgin Islands', ChatifyVectors.vir),
  Country('+092', 'VG', 'Виргинские Острова (Великобритания)', 'British Virgin Islands', ChatifyVectors.vgb),
  Country('+670', 'TL', 'Восточный Тимор','Timor Lorosa’e', ChatifyVectors.tls),
  Country('+84', 'VN', 'Вьетнам', 'Việt Nam', ChatifyVectors.vnm),
  Country('+241', 'GA', 'Габон', 'Gabon', ChatifyVectors.gab),
  Country('+220', 'GM', 'Гамбия', 'Gambia', ChatifyVectors.gmb),
  Country('+590', 'GP', 'Гваделупа', 'Guadeloupe', ChatifyVectors.guf),
  Country('+995', 'GE', 'Грузия', 'საქართველო', ChatifyVectors.geo),
  Country('+49', 'DE', 'Германия', 'Deutschland', ChatifyVectors.deu),
  Country('+44', 'GG', 'Гернси', 'Guernsey', ChatifyVectors.ggy),
  Country('+350', 'GI', 'Гибралтар', 'Gibraltar', ChatifyVectors.gib),
  Country('+30', 'GR', 'Греция', 'Ελλάδα', ChatifyVectors.grc),
  Country('+299', 'GL', 'Гренландия', 'Kalaallit Nunaat', ChatifyVectors.grl),
  Country('+502', 'GT','Гватемала', 'Guatemala', ChatifyVectors.gtm),
  Country('+224', 'GN', 'Гвинея', 'Guinée', ChatifyVectors.gin),
  Country('+245', 'GW', 'Гвинея-Бисау', 'Guiné-Bissau', ChatifyVectors.gnb),
  Country('+592', 'GY', 'Гайана', 'Guyana', ChatifyVectors.guy),
  Country('+509', 'HT', 'Гаити', 'Haïti', ChatifyVectors.hti),
  Country('+504', 'HN', 'Гондурас', 'Honduras', ChatifyVectors.hnd),
  Country('+852', 'HK', 'Гонконг', '香港', ChatifyVectors.hkg),
  Country('+473', 'GD', 'Гренада', 'Grenada', ChatifyVectors.grd),
  Country('+995', 'GU', 'Гуам', 'Guinée', ChatifyVectors.gum),
  Country('+45', 'DK', 'Дания', 'Danmark', ChatifyVectors.dnk),
  Country('+832', 'JE', 'Джерси', 'Jersey', ChatifyVectors.jey),
  Country('+253', 'DJ', 'Джибути', 'جيبوتي,', ChatifyVectors.dji),
  Country('+1767', 'DM', 'Доминика', 'Dominica', ChatifyVectors.dma),
  Country('+809', 'DO', 'Республика Доминикана', 'República Dominicana', ChatifyVectors.dom),
  Country('+20', 'EG', 'Египет', 'مصر', ChatifyVectors.egy),
  Country('+260', 'ZM', 'Замбия', 'Zambia', ChatifyVectors.zmb),
  Country('+263', 'ZW', 'Зимбабве', 'Zimbabwe', ChatifyVectors.zwe),
  Country('+972', 'IL', 'Израиль', '‏יִשְׂרָאֵל,', ChatifyVectors.isr),
  Country('+91', 'IN', 'Индия', 'भारतहिंदुस्तान', ChatifyVectors.ind),
  Country('+62', 'ID', 'Индонезия', 'Indonesia', ChatifyVectors.idn),
  Country('+962', 'JO', 'Иордания','الأردن', ChatifyVectors.jor),
  Country('+98', 'IR', 'Иран', 'ایران', ChatifyVectors.irn),
  Country('+964', 'IQ', 'Ирак', 'الْعِرَاق', ChatifyVectors.irq),
  Country('+353', 'IE', 'Ирландия','Éire', ChatifyVectors.irl),
  Country('+354', 'IS', 'Исландия','Iceland', ChatifyVectors.isl),
  Country('+34', 'ES', 'Испания', 'España', ChatifyVectors.esp),
  Country('+39', 'IT', 'Италия', 'Italia', ChatifyVectors.ita),
  Country('+967', 'YE', 'Йемен', 'ٱلْيَمَن', ChatifyVectors.yem),
  Country('+7', 'KZ', 'Казахстан', 'Қазақстан', ChatifyVectors.kaz),
  Country('+254', 'KE', 'Кения', 'Kenya', ChatifyVectors.ken),
  Country('+686', 'KI', 'Кирибати', 'Kiribati', ChatifyVectors.kir),
  Country('+855', 'KH', 'Камбоджа', 'កម្ពុជា', ChatifyVectors.khm),
  Country('+237', 'CM', 'Камерун', 'Cameroun', ChatifyVectors.cmr),
  Country('+1', 'CA', 'Канада', 'Canada', ChatifyVectors.can),
  Country('+238', 'CV', 'Кабо-Верде', 'Cabo Verde', ChatifyVectors.cpv),
  Country('+1345', 'KY', 'Каймановы Острова', 'Cayman Islands', ChatifyVectors.cym),
  Country('+34', 'CT', 'Каталония', 'Catalunya', ChatifyVectors.cat),
  Country('+974', 'QA', 'Катар', 'قطر', ChatifyVectors.qat),
  Country('+86', 'CN', 'Китай', '中国', ChatifyVectors.chn),
  Country('+506', 'CR', 'Коста-Рика', 'Costa Rica', ChatifyVectors.cri),
  Country('+383', 'XK', 'Косово', 'Kosovё', ChatifyVectors.kos),
  Country('+53', 'CU', 'Куба', 'Cuba', ChatifyVectors.cub),
  Country('+599', 'CW', 'Кюрасао', 'Land Curaçao', ChatifyVectors.cuw),
  Country('+357', 'CY', 'Кипр', 'Κύπρος', ChatifyVectors.cyp),
  Country('+61', 'CC', 'Кокосовые острова', 'Kapelauan Cocos (Keepling)', ChatifyVectors.cck),
  Country('+57', 'CO', 'Колумбия', 'Colombia', ChatifyVectors.col),
  Country('+242', 'CG', 'Конго-Браззавиль', 'Congo-Brazzaville', ChatifyVectors.cog),
  Country('+269', 'KM', 'Коморы', 'Komori', ChatifyVectors.com),
  Country('+225', 'CI', 'Кот-д`Ивуар', 'Côte d’Ivoire', ChatifyVectors.civ),
  Country('+965', 'KW', 'Кувейт', 'الكويت', ChatifyVectors.kwt),
  Country('+996', 'KG', 'Киргизия', 'Кыргызстан', ChatifyVectors.kgz),
  Country('+856', 'LA', 'Лаос', 'ລາວ', ChatifyVectors.lao),
  Country('+371', 'LV', 'Латвия', 'Latvija', ChatifyVectors.lva),
  Country('+961', 'LB', 'Ливан', 'لُبْنَان', ChatifyVectors.lbn),
  Country('+266', 'LS', 'Лесото', 'Lesotho', ChatifyVectors.lso),
  Country('+231', 'LR', 'Либерия', 'Liberia', ChatifyVectors.lbr),
  Country('+218', 'LY', 'Ливия', 'ليبيا', ChatifyVectors.lby),
  Country('+423', 'LI', 'Лихтенштейн', 'Liechtenstein', ChatifyVectors.lie),
  Country('+370', 'LT', 'Литва', 'Lietuva', ChatifyVectors.ltu),
  Country('+352', 'LU', 'Люксембург', 'Lëtzebuerg', ChatifyVectors.lux),
  Country('+853', 'MO', 'Макао', '澳門', ChatifyVectors.mac),
  Country('+261', 'MG', 'Мадагаскар', 'Madagasikara', ChatifyVectors.mdg),
  Country('+265', 'MW', 'Малави', 'Malawi', ChatifyVectors.mwi),
  Country('+212', 'MA', 'Марокко', 'المغرب', ChatifyVectors.mar),
  Country('+60', 'MY', 'Малайзия', 'Malaysia', ChatifyVectors.mys),
  Country('+960', 'MV', 'Мальдивы', 'ހިވެދި ގުޖޭއްރާ', ChatifyVectors.mdv),
  Country('+223', 'ML', 'Мали','Mali', ChatifyVectors.mli),
  Country('+356', 'MT', 'Мальта','Malta', ChatifyVectors.mlt),
  Country('+692', 'MH', 'Маршалловы острова', 'Marshall Islands', ChatifyVectors.mhl),
  Country('+222', 'MR', 'Мавритания', 'موريتانيا', ChatifyVectors.mrt),
  Country('+230', 'MU', 'Маврикий', 'Mauritius', ChatifyVectors.mus),
  Country('+262', 'YT', 'Майотта', 'Mayotte', ChatifyVectors.wlf),
  Country('+52', 'MX', 'Мексика', 'México', ChatifyVectors.mex),
  Country('+691', 'FM', 'Микронезия', 'Micronesia', ChatifyVectors.fsm),
  Country('+373', 'MD', 'Молдавия', 'Moldova', ChatifyVectors.mda),
  Country('+377', 'MC', 'Монако', 'Monaco', ChatifyVectors.mco),
  Country('+976', 'MN', 'Монголия', 'Montserrat', ChatifyVectors.mng),
  Country('+1664', 'MS', 'Монтсеррат', 'Монгол Улс', ChatifyVectors.msr),
  Country('+95', 'MM', 'Мьянма (Бирма)','မြန်မာ', ChatifyVectors.mmr),
  Country('+258', 'MZ', 'Мозамбик', 'Moçambique', ChatifyVectors.moz),
  Country('+264', 'NA', 'Намибия', 'Namibia', ChatifyVectors.nam),
  Country('+674', 'NR', 'Науру', 'Naoero', ChatifyVectors.nru),
  Country('+977', 'NP', 'Непал', 'नेपाल', ChatifyVectors.npl),
  Country('+31', 'NL', 'Нидерланды', 'Nederland', ChatifyVectors.nld),
  Country('+687', 'NC', 'Новая Каледония', 'Nouvelle-Calédonie', ChatifyVectors.ncl),
  Country('+64', 'NZ', 'Новая Зеландия', 'New Zealand', ChatifyVectors.nzl),
  Country('+505', 'NI', 'Никарагуа', 'Nicaragua', ChatifyVectors.nzl),
  Country('+227', 'NE', 'Нигер', 'Niger', ChatifyVectors.ner),
  Country('+234', 'NG', 'Нигерия', 'Nigeria', ChatifyVectors.nga),
  Country('+683', 'NU', 'Ниуэ', 'Niue', ChatifyVectors.niu),
  Country('+47', 'NO', 'Норвегия', 'Norge', ChatifyVectors.nor),
  Country('+971', 'AE', 'Объединенные Арабские Эмираты', 'الإمارات,', ChatifyVectors.are),
  Country('+968', 'OM', 'Оман', 'عُمان', ChatifyVectors.omn),
  Country('+247', 'AC', 'Остров Вознесения', 'Ascension Island', ChatifyVectors.asi),
  Country('+44', 'IM', 'Остров Мэн', 'Isle of Man', ChatifyVectors.imn),
  Country('+682', 'CK', 'Острова Кука', 'Cook Islands', ChatifyVectors.cok),
  Country('+870', 'PN', 'Острова Питкэрн', 'Pitcairn Islands', ChatifyVectors.pcn),
  Country('+61', 'CX', 'Остров Рождества', 'Christmas Island', ChatifyVectors.cxr),
  Country('+290', 'SH', 'Остров Святой Елены', 'St. Elena Island', ChatifyVectors.shn),
  Country('+599', 'KY', 'Острова Кайман', 'Cayman Islands', ChatifyVectors.cym),
  Country('+92', 'PK', 'Пакистан', 'پاکستان', ChatifyVectors.pak),
  Country('+970', 'PS', 'Палестина', 'دولة فلسطي', ChatifyVectors.pse),
  Country('+680', 	'PW', 'Палау', 'Palau', ChatifyVectors.plw),
  Country('+507', 'PA', 'Панама', 'Panamá', ChatifyVectors.pan),
  Country('+675', 'PG', 'Папуа - Новая Гвинея', 'Papua New Guinea', ChatifyVectors.png),
  Country('+595', 'PY', 'Парагвай', 'Paraguay', ChatifyVectors.pry),
  Country('+51', 'PE', 'Перу', 'Perú', ChatifyVectors.per),
  Country('+48', 'PL', 'Польша', 'Polska', ChatifyVectors.pol),
  Country('+351', 'PT', 'Португалия', 'Portugal', ChatifyVectors.prt),
  Country('+620', 'PR', 'Пуэрто-Рико', 'Puerto Rico', ChatifyVectors.pri),
  Country('+262', 'RE', 'Реюньон', 'Réunion', ChatifyVectors.reu),
  Country('+7', 'RU', 'Россия', 'Russia', ChatifyVectors.rus),
  Country('+250', 'RW', 'Руанда', 'Rwandan', ChatifyVectors.rwa),
  Country('+40', 'RO', 'Румыния', 'România', ChatifyVectors.rou),
  Country('+503', 'SV', 'Сальвадор', 'El Salvador', ChatifyVectors.slv),
  Country('+685', 'WS', 'Самоа', 'Samoa', ChatifyVectors.wsm),
  Country('+378', 'SM', 'Сан-Марино', 'San Marino', ChatifyVectors.smr),
  Country('+239', 'ST', 'Сан-Томе и Принсипи', 'São Tomé and Príncipe', ChatifyVectors.stp),
  Country('+966', 'SA', 'Саудовская Аравия', 'ٱلسُّعُوْدِيَّة العربيّة', ChatifyVectors.sau),
  Country('+389', 'MK', 'Северная Македония', 'Северна Македонија', ChatifyVectors.mkd),
  Country('+1670', 'MP', 'Северные Марианские Острова', 'Northern Mariana Islands', ChatifyVectors.mnp),
  Country('+590', 'BL', 'Сен-Бартелеми', 'Saint-Barthélemy', ChatifyVectors.wlf),
  Country('+850', 'KP', 'Северная Корея', '北朝鮮', ChatifyVectors.prk),
  Country('+221', 'SN', 'Сенегал', 'Sénégal', ChatifyVectors.sen),
  Country('+221', 'VC', 'Сент-Винсент и Гренадины', 'St. Vincent & Grenadines', ChatifyVectors.vct),
  Country('+659', 'KN', 'Сент-Китс и Невис', 'St. Kitts &amp; Nevis', ChatifyVectors.kna),
  Country('+221', 'LC', 'Сент-Люсия', 'Saint Lucia', ChatifyVectors.ica),
  Country('+381', 'RS', 'Сербия', 'Србија', ChatifyVectors.srb),
  Country('+248', 'SC', 'Сейшельские острова', 'Sesel', ChatifyVectors.syc),
  Country('+232', 'SL', 'Сьерра-Леоне', 'Sierra Leone', ChatifyVectors.sle),
  Country('+65', 'SG', 'Сингапур', 'Singapura', ChatifyVectors.sgp),
  Country('+534', 'SX', 'Синт-Мартен', 'Sint Maarten', ChatifyVectors.wlf),
  Country('+421', 'SK', 'Словакия', 'Slovensko', ChatifyVectors.svk),
  Country('+386', 'SI', 'Словения', 'Slovenija', ChatifyVectors.svn),
  Country('+1', 'US', 'Соединенные Штаты Америки', 'United States of America', ChatifyVectors.usa),
  Country('+677', 'SB', 'Соломоновы острова', 'Solomon Islands', ChatifyVectors.slb),
  Country('+252', 'SO', 'Сомали', 'Soomaaliya', ChatifyVectors.som),
  Country('+508', 'PM', 'Сен-Пьер и Микелон', 'Saint-Pierre et Miquelon', ChatifyVectors.spm),
  Country('+249', 'SD', 'Судан', 'السودان', ChatifyVectors.sdn),
  Country('+597', 'SR', 'Суринам', 'Suriname', ChatifyVectors.sur),
  Country('+963', 'SY', 'Сирия', 'سُورِيَة', ChatifyVectors.syr),
  Country('+886', 'TW', 'Тайвань', '台灣', ChatifyVectors.twn),
  Country('+992', 'TJ', 'Таджикистан', 'Тоҷикистон', ChatifyVectors.tjk),
  Country('+255', 'TZ', 'Танзания', 'Tanzania', ChatifyVectors.tza),
  Country('+66', 'TH', 'Таиланд', 'ประเทศไทย', ChatifyVectors.tha),
  Country('+228', 'TG', 'Того', 'Togo,', ChatifyVectors.tgo),
  Country('+690', 'TK', 'Токелау', 'Tokelau,', ChatifyVectors.tkl),
  Country('+676', 'TO', 'Тонга', 'Tonga', ChatifyVectors.ton),
  Country('+1868', 'TT', 'Тринидад и Тобаго', 'Trinidad & Tobago', ChatifyVectors.tto),
  Country('+216', 'TN', 'Тунис', 'تونس', ChatifyVectors.tun),
  Country('+90', 'TR', 'Турция', 'Türkiye', ChatifyVectors.tur),
  Country('+993', 'TM', 'Туркменистан', 'Türkmenistan', ChatifyVectors.tkm),
  Country('+688', 'TV', 'Тувалу', 'Tuvalu', ChatifyVectors.tuv),
  Country('+256', 'UG', 'Уганда', 'Uganda', ChatifyVectors.uga),
  Country('+380', 'UA', 'Украина', 'Україна', ChatifyVectors.ukr),
  Country('+598', 'UY', 'Уругвай', 'Uruguay', ChatifyVectors.ury),
  Country('+998', 'UZ', 'Узбекистан', 'Oʻzbekiston', ChatifyVectors.uzb),
  Country('+681', 'WF', 'Уоллис и Футуна', 'Wallis-et-Futuna', ChatifyVectors.wlf),
  Country('+298', 'FO', 'Фарерские острова', '', ChatifyVectors.fro),
  Country('+679', 'FJ', 'Фиджи', 'Fiji', ChatifyVectors.fji),
  Country('+63', 'PH', 'Филиппины', 'Pilipinas', ChatifyVectors.phl),
  Country('+358', 'FI', 'Финляндия', 'Suomi', ChatifyVectors.fin),
  Country('+500', 'FK', 'Фолклендские острова', 'Falkland Islands', ChatifyVectors.flk),
  Country('+33', 'FR', 'Франция', 'France', ChatifyVectors.fra),
  Country('+689', 'PF', 'Французская Полинезия', 'Polynésie française', ChatifyVectors.pyf),
  Country('+594', 'GF', 'Французская Гвиана', 'Guyane Française', ChatifyVectors.giu),
  Country('+385', 'HR', 'Хорватия', 'Hrvatska', ChatifyVectors.hrv),
  Country('+236', 'CF', 'Центрально-Африканская Республика', 'République Centrafricaine', ChatifyVectors.caf),
  Country('+235', 'TD', 'Чад', 'Tchad', ChatifyVectors.tcd),
  Country('+382', 'ME', 'Черногория', 'Црна Гора / Crna Gora', ChatifyVectors.mne),
  Country('+420', 'CZ', 'Чехия', 'Česko', ChatifyVectors.cze),
  Country('+56', 'CL', 'Чили', 'Chile', ChatifyVectors.chl),
  Country('+41', 'CH', 'Швейцария', 'Schweiz', ChatifyVectors.che),
  Country('+46', 'SE', 'Швеция', 'Sverige', ChatifyVectors.swe),
  Country('+94', 'LK', 'Шри-Ланка', 'ශ්‍රී ලංකාව', ChatifyVectors.lka),
  Country('+47', 'SJ', 'Шпицберген', 'Svalbard', ChatifyVectors.nor),
  Country('+240', 'GQ', 'Экваториальная Гвинея', 'Guinea Ecuatorial', ChatifyVectors.gnq),
  Country('+593', 'EC', 'Эквадор', 'Ecuador', ChatifyVectors.ecu),
  Country('+291', 'ER', 'Эритрея', 'إرتريا', ChatifyVectors.eri),
  Country('+268', 'SZ', 'Эсватини', 'Eswatini', ChatifyVectors.swz),
  Country('+372', 'EE', 'Эстония', 'Eesti', ChatifyVectors.est),
  Country('+251', 'ET', 'Эфиопия', 'ኢትዮጵያ', ChatifyVectors.eth),
  Country('+27', 'ZA', 'Южная Африка', 'South Africa', ChatifyVectors.zaf),
  Country('+82', 'KR', 'Южная Корея', '南韓', ChatifyVectors.kor),
  Country('+211', 'SS', 'Южный Судан', 'South Sudan', ChatifyVectors.ssd),
  Country('+876', 'JM', 'Ямайка', 'Jamaica', ChatifyVectors.jam),
  Country('+81', 'JP', 'Япония', '日本', ChatifyVectors.jpn),
];

Widget buildCountryList(BuildContext context) {
  final localizations = AppLocalizations.of(context);

  return ListView.builder(
    itemCount: countries.length,
    itemBuilder: (context, index) {
      final country = countries[index];
      final countryName = localizations?.translate('countries.${country.name}') ?? country.name;

      return ListTile(
        leading: SvgPicture.asset(country.flag),
        title: Text(countryName),
        subtitle: Text(country.nativeName),
      );
    },
  );
}

String? getCountryNameByCode(String code) {
  final country = countries.firstWhere((country) => country.code.replaceAll('+', '') == code.replaceAll('+', ''),
    orElse: () => Country('', '', '', '', ''),
  );
  return country.name.isNotEmpty ? country.name : null;
}
